# Generated by Django 5.2.5 on 2025-08-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('hobby', '趣味'), ('study', '学習'), ('other', 'その他')], default='other', max_length=50),
        ),
    ]
